package uz.duke.worldbuilder;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import uz.duke.dungeon.content.DungeonSettings;
import uz.duke.dungeon.stage.StageCheck;
import uz.duke.dungeon.stage.StageFile;

/**
 * The stage the game ships with, written out again.
 *
 * <p>A worked example rather than a level anybody laboured over: one seed, its
 * own monsters left where the generator put them, and a name. What it is for is
 * to be the thing an author opens first — {@code ./gradlew :worldbuilder:run
 * --args="dungeon/src/main/resources/stages/first.stage"} — and the thing the
 * game's own tests can load to prove that a shipped stage is a playable one.
 *
 * <p>Generated by a task rather than saved by hand out of the builder, because a
 * file nobody can rebuild is a file nobody dares change. Re-run it with:
 *
 * <pre>{@code ./gradlew :worldbuilder:writeExampleStage}</pre>
 */
public final class ExampleStage {

    /**
     * A seed with a floor worth walking on it — chosen by looking, which is what
     * the builder is for. Any seed makes a valid stage; this one makes a good one.
     */
    private static final long SEED = 20260911L;

    private static final Path WHERE =
            Path.of("dungeon", "src", "main", "resources", "stages", "first.stage");

    private ExampleStage() {
    }

    public static void main(String[] args) {
        var settings = DungeonSettings.load();
        var draft = StageDraft.generate(SEED, settings);
        draft.setId("first");
        draft.setName("The First Descent");
        draft.setDescription("One floor, drawn once and never again — learn it, then win it.");
        draft.setDifficulty(1);
        draft.setPlayers(1);

        var stage = draft.toStage();
        var problems = StageCheck.problems(stage, settings);
        if (!problems.isEmpty()) {
            // Never ship a stage the game would refuse. If the settings drift far
            // enough to make this seed unplayable, that is worth stopping for.
            throw new IllegalStateException("the example stage is broken: " + problems);
        }

        var path = args.length > 0 ? Path.of(args[0]) : WHERE;
        try {
            Files.createDirectories(path.toAbsolutePath().getParent());
            Files.writeString(path, StageFile.write(stage), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("could not write " + path, e);
        }
        System.out.println("wrote " + path.toAbsolutePath());
    }
}
