package uz.duke.worldbuilder;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import uz.duke.dungeon.content.DungeonSettings;
import uz.duke.dungeon.gen.Layout;
import uz.duke.dungeon.stage.StageCheck;
import uz.duke.dungeon.stage.StageFile;

/**
 * The stage the game ships with, written out again.
 *
 * <p>A worked example rather than a level anybody laboured over: one seed, its
 * own monsters left where the generator put them, and a name. What it is for is
 * to be the thing an author opens first — {@code ./gradlew :worldbuilder:run
 * --args="dungeon/src/main/resources/data/maps/first.duke"} — and the thing the
 * game's own tests can load to prove that a shipped stage is a playable one.
 *
 * <p>Generated by a task rather than saved by hand out of the builder, because a
 * file nobody can rebuild is a file nobody dares change. Re-run it with:
 *
 * <pre>{@code ./gradlew :worldbuilder:writeExampleStage}</pre>
 */
public final class ExampleStage {

    private static final Path FOLDER =
            Path.of("dungeon", "src", "main", "resources", "data", "maps");

    /**
     * One stage to write out.
     *
     * @param seed       chosen by looking, which is what the builder is for — any
     *                   seed makes a valid stage and these two make good ones
     * @param difficulty the depth it is fought at
     */
    private record Example(String id, String name, String about, long seed, int difficulty,
            int width, int height, int rooms) {
    }

    /**
     * The two the game ships with, and they are shipped as a pair on purpose: one
     * of them is the size and danger of an ordinary floor, and the other is what a
     * stage can be that a generated floor never is.
     *
     * <p>The large one is kept to about four times the shipped floor's area rather
     * than as large as the builder will go. The generator, the checks and the
     * simulation are happy far beyond this — a 200 by 150 floor with seventy rooms
     * draws in well under a tenth of a second and passes every check — but the 3D
     * client builds <em>one Geometry per stone cell</em> and batches none of them,
     * which is a thousand of them on the shipped floor and twenty-two thousand on
     * that one. Shipping a stage that is a slideshow would be a poor advertisement
     * for being able to build large ones.
     */
    private static final Example[] EXAMPLES = {
        new Example("first", "The First Descent",
                "One floor, drawn once and never again — learn it, then win it.",
                20260911L, 1, 50, 36, 9),
        new Example("deep", "The Long Dark",
                "Four times the floor and eight times down. Bring everything.",
                20260912L, 8, 100, 76, 28),
    };

    private ExampleStage() {
    }

    public static void main(String[] args) {
        var settings = DungeonSettings.load();
        var folder = args.length > 0 ? Path.of(args[0]) : FOLDER;
        for (var example : EXAMPLES) {
            write(settings, example, folder.resolve(example.id() + ".duke"));
        }
    }

    private static void write(DungeonSettings settings, Example example, Path path) {
        var draft = StageDraft.generate(example.seed(), settings,
                Layout.sized(settings, example.width(), example.height(), example.rooms()),
                example.difficulty());
        draft.setId(example.id());
        draft.setName(example.name());
        draft.setDescription(example.about());
        draft.setPlayers(1);

        var stage = draft.toStage();
        var problems = StageCheck.problems(stage, settings);
        if (!problems.isEmpty()) {
            // Never ship a stage the game would refuse. If the settings drift far
            // enough to make one of these seeds unplayable, that is worth stopping
            // for rather than writing the file anyway.
            throw new IllegalStateException(example.id() + " is broken: " + problems);
        }

        try {
            Files.createDirectories(path.toAbsolutePath().getParent());
            Files.writeString(path, StageFile.write(stage), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("could not write " + path, e);
        }
        System.out.println("wrote " + path.toAbsolutePath() + " — " + stage.floor().rooms().size()
                + " rooms, " + stage.floor().monsters().size() + " monsters, at depth "
                + stage.difficulty());
    }
}
